version: '3.8'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=.Y4r.3G*YaR4bjj
      - POSTGRES_USER=nomad
      - POSTGRES_DB=db-blogs
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    image: node-blog-app
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
    ports:
      - 13000:8383
volumes:
  pgdata: {}